# Generated by Django 5.2.3 on 2026-03-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Période')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Période de Paie',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire brut')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cotisations')),
                ('total_bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Primes')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire net')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé'), ('paid', 'Payé')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollperiod')),
            ],
            options={
                'verbose_name': 'Fiche de Paie',
                'ordering': ['-period__start_date'],
                'unique_together': {('employee', 'period')},
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('bonus', 'Prime'), ('deduction', 'Retenue')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_percentage', models.BooleanField(default=False)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payslip')),
            ],
            options={
                'verbose_name': 'Élément de Paie',
            },
        ),
    ]
