# Generated by Django 5.2.3 on 2026-04-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_role'),
        ('employees', '0006_remove_site_location'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['organization', 'start_date'], name='payroll_pay_organiz_2d3121_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['is_closed'], name='payroll_pay_is_clos_761151_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employee', 'status'], name='payroll_pay_employe_cb591a_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['period', 'status'], name='payroll_pay_period__f539cf_idx'),
        ),
    ]
