# Generated by Django 5.2.3 on 2026-04-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
