# Generated by Django 5.2.3 on 2026-04-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_auditlog_user_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasadmin',
            name='supabase_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID Supabase'),
        ),
    ]
