# Generated by Django 5.2.3 on 2026-04-04 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_auditlog_user_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_super_admin', models.BooleanField(default=False)),
                ('supabase_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID Supabase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saas_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrateur SaaS',
                'verbose_name_plural': 'Administrateurs SaaS',
            },
        ),
    ]
