# Generated by Django 5.2.3 on 2026-04-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_setup_saas_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('Rh', 'Ressources Humaines'), ('manager', 'Manager'), ('employee', 'Employé'), ('support', 'Support Technique'), ('commercial', 'Agent Commercial')], default='employee', max_length=20),
        ),
    ]
