# Generated by Django 5.2.3 on 2026-04-12 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='FCFA', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('overdue', 'En retard'), ('canceled', 'Annulé')], default='pending', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('file_url', models.URLField(blank=True, help_text='Lien vers la facture PDF stockée sur Supabase Storage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Facture',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='activated_modules',
            field=models.JSONField(blank=True, default=dict, help_text="Modules activés: {'recruitment': true, 'payroll': true, ...}"),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Actif'), ('past_due', 'Paiement en attente'), ('canceled', 'Résilié'), ('suspended', 'Suspendu')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_employees',
            field=models.IntegerField(default=10, help_text="Limite d'employés selon le plan"),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter (Indépendant/PME)'), ('pro', 'Pro (Entreprise en croissance)'), ('premium', 'Premium (Grande Entreprise)'), ('legacy', 'Ancien Plan')], default='starter', max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='accounts_au_resourc_30880d_idx'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.organization'),
        ),
    ]
