# Generated by Django 5.2.3 on 2026-04-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_invoice_organization_activated_modules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_trusted_partner',
            field=models.BooleanField(default=False, verbose_name='Partenaire de confiance'),
        ),
    ]
