# Generated by Django 5.2.3 on 2026-04-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cnss_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro CNSS'),
        ),
        migrations.AddField(
            model_name='employee',
            name='family_parts',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='Parts IRPP'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_expat',
            field=models.BooleanField(default=False, verbose_name='Expatrié'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sector',
            field=models.CharField(choices=[('petrole', 'Pétrole & Mines'), ('bois', 'Exploitation Forestière'), ('btp', 'BTP & Construction'), ('agro', 'Agro-industrie'), ('commerce', 'Commerce & Services')], default='commerce', max_length=50, verbose_name='Secteur'),
        ),
        migrations.AddField(
            model_name='employee',
            name='site_location',
            field=models.CharField(choices=[('libreville', 'Libreville'), ('port-gentil', 'Port-Gentil'), ('franceville', 'Franceville'), ('moanda', 'Moanda'), ('site_distant', 'Site Distant (Exploitation)')], default='libreville', max_length=50, verbose_name='Site'),
        ),
    ]
