# Generated by Django 5.2.3 on 2026-04-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_role'),
        ('employees', '0002_employee_cnss_number_employee_family_parts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='site_location',
            field=models.CharField(choices=[('libreville', 'Libreville'), ('port-gentil', 'Port-Gentil'), ('franceville', 'Franceville'), ('moanda', 'Moanda'), ('site_distant', 'Site Distant (Exploitation)')], default='libreville', max_length=50, verbose_name='Site (Obsolète)'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du site/lieu')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Lieu/Site',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.location', verbose_name='Site/Lieu'),
        ),
    ]
