# Generated by Django 5.2.3 on 2026-04-04 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_role'),
        ('employees', '0003_alter_employee_site_location_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='site_location',
            field=models.CharField(blank=True, choices=[('libreville', 'Libreville'), ('port-gentil', 'Port-Gentil'), ('franceville', 'Franceville'), ('moanda', 'Moanda'), ('site_distant', 'Site Distant (Exploitation)')], default='libreville', max_length=50, null=True, verbose_name='Site (Obsolète)'),
        ),
        migrations.CreateModel(
            name='ArchivedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Poste / Rôle')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('seniority', models.CharField(blank=True, max_length=50, verbose_name='Ancienneté / Durée')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.EmailField(blank=True, max_length=254, verbose_name='Supprimé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_employees', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Ancien Employé',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
