# Generated by Django 5.2.3 on 2026-04-11 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_role'),
        ('employees', '0004_alter_employee_site_location_archivedemployee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedemployee',
            name='cnss_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='N° CNSS'),
        ),
        migrations.AddField(
            model_name='archivedemployee',
            name='contract_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.AddField(
            model_name='archivedemployee',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AlterField(
            model_name='archivedemployee',
            name='seniority',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ancienneté'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='site_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Site (Obsolète — utiliser location FK)'),
        ),
        migrations.AddIndex(
            model_name='archivedemployee',
            index=models.Index(fields=['organization', 'deleted_at'], name='employees_a_organiz_976824_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['organization', 'is_active'], name='employees_d_organiz_6ea168_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'location'], name='employees_e_organiz_f18180_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'contract_type'], name='employees_e_organiz_423ead_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'is_expat'], name='employees_e_organiz_beb057_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'hire_date'], name='employees_e_organiz_a3aa13_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['organization', 'is_active'], name='employees_p_organiz_588899_idx'),
        ),
    ]
