# Generated by Django 5.2.3 on 2026-04-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_role'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['organization', 'status'], name='job_org_status_idx'),
        ),
    ]
