# Generated by Django 5.2.3 on 2026-04-11 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_role'),
        ('employees', '0006_remove_site_location'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='accounts.organization'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['organization', 'status'], name='leave_org_status_idx'),
        ),
    ]
