# Generated by Django 5.2.3 on 2026-03-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Demande Heures Sup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(verbose_name='Arrivée')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Départ')),
                ('break_minutes', models.IntegerField(default=60, verbose_name='Pause (min)')),
                ('notes', models.TextField(blank=True)),
                ('is_remote', models.BooleanField(default=False, verbose_name='Télétravail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Pointage',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
