# Generated by Django 5.2.3 on 2026-04-11 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_role'),
        ('employees', '0006_remove_site_location'),
        ('time_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], max_length=3, verbose_name='Type de scan')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='Scanné à')),
            ],
            options={
                'verbose_name': 'Scan QR',
                'verbose_name_plural': 'Scans QR',
            },
        ),
        migrations.CreateModel(
            name='QRSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token HMAC')),
                ('date', models.DateField(verbose_name='Date du QR')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration')),
                ('is_active', models.BooleanField(default=True, verbose_name='QR actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Session QR',
                'verbose_name_plural': 'Sessions QR',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='overtimerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande Heures Sup', 'verbose_name_plural': 'Demandes Heures Sup'},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Pointage', 'verbose_name_plural': 'Pointages'},
        ),
        migrations.AddField(
            model_name='timeentry',
            name='scanned_via_qr',
            field=models.BooleanField(default=False, verbose_name='Pointé par QR'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='employees.employee', verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='hours',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Heures demandées'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='reason',
            field=models.TextField(verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='employees.employee', verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['employee', 'status'], name='ot_employee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['employee', 'date'], name='tt_employee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['employee', '-date'], name='tt_employee_date_desc_idx'),
        ),
        migrations.AddField(
            model_name='qrscan',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='employees.employee', verbose_name='Employé'),
        ),
        migrations.AddField(
            model_name='qrsession',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='accounts.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='qrscan',
            name='qr_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='time_tracking.qrsession', verbose_name='Session QR'),
        ),
        migrations.AddIndex(
            model_name='qrsession',
            index=models.Index(fields=['token'], name='qr_token_idx'),
        ),
        migrations.AddIndex(
            model_name='qrsession',
            index=models.Index(fields=['organization', 'date'], name='qr_org_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qrsession',
            unique_together={('organization', 'date')},
        ),
        migrations.AddIndex(
            model_name='qrscan',
            index=models.Index(fields=['qr_session', 'employee'], name='scan_session_emp_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qrscan',
            unique_together={('qr_session', 'employee', 'scan_type')},
        ),
    ]
