# Generated by Django 5.2.3 on 2026-03-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50, verbose_name='Période')),
                ('overall_rating', models.IntegerField(default=0, verbose_name='Note globale (1-5)')),
                ('strengths', models.TextField(blank=True, verbose_name='Points forts')),
                ('improvements', models.TextField(blank=True, verbose_name="Axes d'amélioration")),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('in_progress', 'En cours'), ('completed', 'Terminé')], default='draft', max_length=20)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employees.employee')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_reviews', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0, verbose_name='Progression (%)')),
                ('status', models.CharField(choices=[('not_started', 'Non démarré'), ('in_progress', 'En cours'), ('completed', 'Atteint'), ('not_achieved', 'Non atteint')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='employees.employee')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='performance.performancereview')),
            ],
            options={
                'verbose_name': 'Objectif',
                'ordering': ['-created_at'],
            },
        ),
    ]
