# Generated by Django 5.2.3 on 2026-04-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_site_location'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['employee', 'status'], name='performance_employe_71e0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['review'], name='performance_review__19945d_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['employee', 'status'], name='performance_employe_57a8d8_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['reviewer'], name='performance_reviewe_446209_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['period'], name='performance_period_dd8465_idx'),
        ),
    ]
